openapi: 3.0.0
info:
  title: Author's Haven
  description: Author's Haven is a community of like minded authors to foster
    inspiration and innovation by leveraging the modern web Api on [https://ah-dahlia.herokuapp.com/](https://ah-dahlia-staging.herokuapp.com/)

  license:
    name: MIT License
    url: https://opensource.org/licenses/MIT
  version: 1.0.0

externalDocs:
  description: Checkout the GitHub repo
  url: https://github.com/andela/dahlia-ah-backend

servers:
- url: /api/
  description: Local host
- url: https://ah-dahlia-staging.herokuapp.com/api/
  description: Heroku deployment

tags:
- name: Users
  description: Operations available for user endpoints

security:
- ApiKeyAuth: []
paths:
  /users:
    post:
      tags:
        - Users
      summary: Creates a new user
      requestBody:
        description: fields containing user data
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserRegisterInput'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/UserRegisterInput'
        required: true
      responses:
        201:
          description: user created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthResponse'
        400:
          description: bad input parameter
        409:
          description: resource already exists
        500:
          description: internal server error
  /users/login:
    post:
      tags:
        - Users
      summary: Login an existing user
      requestBody:
        description: fields containing user login data
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserLoginInput'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/UserLoginInput'
        required: true
      responses:
        200:
          description: user login successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthResponse'
        400:
          description: bad input parameter
        401:
          description: authorization error
        409:
          description: resource already exists
        500:
          description: internal server error

components:
  schemas:
    User:
      required:
      - firstname
      - lastname
      - email
      - username
      type: object
      properties:
        firstname:
          type: string
          example: john
        lastname:
          type: string
          example: doe
        email:
          type: string
          example: johndoe@email.com
        username:
          type: string
          example: johnnydoe12
        bio:
          type: string
          example: I am awesome
        avatarURL:
          type: string
          example: https://your_avatar.com/your_avatar.jpg
        phoneNo:
          type: string
          example: 2347012345678
        address:
          type: string
          example: 123 Eve's Garden Road, Eden
    UserRegisterInput:
      required:
        - firstname
        - lastname
        - email
        - password
      type: object
      properties:
        firstname:
          type: string
          example: john
        lastname:
          type: string
          example: doe
        username:
          type: string
          example: johnnydoe12
        email:
          type: string
          example: johndoe@email.com
        password:
          type: string
          example: Flyplane_x22
    UserLoginInput:
      properties:
        email:
          type: string
          example: johndoe@email.com
        password:
          type: string
          example: Flyplane_x22
    AuthResponse:
      type: object
      properties:
        email:
          type: string
        token:
          type: string
        username:
          type: string
        bio:
         type: string
        image:
          type: string
  
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      name: Authorization
      in: header
