openapi: 3.0.0
info:
  title: Author's Haven
  description: Author's Haven is a community of like minded authors to foster
    inspiration and innovation by leveraging the modern web Api on [https://ah-dahlia.herokuapp.com/](https://ah-dahlia-staging.herokuapp.com/)

  license:
    name: MIT License
    url: https://opensource.org/licenses/MIT
  version: 1.0.0

externalDocs:
  description: Checkout the GitHub repo
  url: https://github.com/andela/dahlia-ah-backend

servers:
- url: /api/v1
  description: Local host
- url: https://ah-dahlia-staging.herokuapp.com/api/v1
  description: Heroku Staging deployment
- url: https://ah-dahlia.herokuapp.com/api/v1
  description: Heroku Production deployment

tags:
- name: Users
  description: Operations available for user endpoints

paths:
  /users:
    post:
      tags:
        - Users
      summary: Creates a new user.
      security:
      - ApiKeyAuth: []
      requestBody:
        description: fields containing user data
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserRegisterInput'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/UserRegisterInput'
        required: true
      responses:
        201:
          description: user created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthResponse'
        400:
          description: bad input parameter
          content:
            application/json:
              schema:
                type: object
                properties: 
                  errors:
                    type: array
                    items:
                      type: object
                      properties:
                        field:
                          type: string
                          example: email
                        message:
                          type: string
                          example: the email address you supplied is invalid
        409:
          description: resource already exists
        500:
          description: internal server error 
  /novels:
    post:
      tags:
        - Novels
      summary: Creates a new novel
      security:
      - ApiKeyAuth: []
      requestBody:
        description: fields containing novel data
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NovelInput'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/NovelInput'
        required: true
      responses:
        201:
          description: novel created successfully
        401:
          description: Authentication failed
        409:
          description: resource already exists
        500:
          description: internal server error                  
  /users/login:
    post:
      tags:
        - Users
      summary: Login an existing user with email
      requestBody:
        description: fields containing user login data
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserLoginInput'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/UserLoginInput'
        required: true
      responses:
        200:
          description: user login successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthResponse'
        400:
          description: bad input parameter
        409:
          description: resource already exists
        500:
          description: internal server error
  /auth/forgotpassword:
    post:
      summary: Forgot password
      description: Sends an email to a user with the reset password link
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
      responses:
        200:
          description: successful request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StandardServerResponse'
        404:
          description: user not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StandardServerResponse'
        500:
          description: server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StandardServerResponse'
  /novels/{slug}/comments:
    post:
      summary: Creates a comment
      description: Post a comment on a novel
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                commentBody:
                  type: string
      parameters:
        - name: slug
          in: path
          required: true
          schema:
            type: string
      responses:
        201:
          description: succesful request, entity created
          content:
            application/json:
              schema:
                type: object
                properties:
                  comment:
                    type: object
                    properties:
                      novel:
                        type: string
                        example: The Good Book
                      commenter:
                        type: string
                        example: bigShaq004
                      commentBody:
                        type: string
                        example: I really love this book
                      updatedAt:
                        type: string
                        example: '2019-08-05T14:17:58.518Z'
        400:
          description: bad request
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: array
                    items:
                      type: object
                      properties:
                        field:
                          type: string
                          example: commentBody
                        message:
                          type: string
                          example: commentBody cannot be empty
        401:
          description: unauthorized access
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: invalid token
        403:
          description: forbidden access
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: you have to be subscribed to comment on a novel
        404:
          description: entity not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: novel not found
        500:
          description: server error
  '/profiles/{userId}':
    get:
      tags:
        - Users
      summary: View a user profile.
      security:
      - ApiKeyAuth: []
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: integer
            example: '1'
      responses:
        200:
          description: profile details of user
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Profile'
        404:
          description: user not found
          content:
            application/json:
              schema:
                type: object
                properties: 
                  error:
                    type: object
                    properties:
                      message:
                          type: string
                          example: 'user not found'
  /novels/{slug}/comments/{parentId}:
    post:
      summary: Creates a reply
      description: Reply a parent comment
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                commentBody:
                  type: string
      parameters:
        - name: slug
          in: path
          required: true
          schema:
            type: string
        - name: parentId
          in: path
          required: true
          schema:
            type: integer
      responses:
        201:
          description: succesful request, entity created
          content:
            application/json:
              schema:
                type: object
                properties:
                  reply:
                    type: object
                    properties:
                      novel:
                        type: string
                        example: The Good Book
                      parentComment:
                        type: string
                        example: this book is really nice
                      replier:
                        type: string
                        example: I really love this book
                      replyBody:
                        type: string
                        example: yeah I think so too
                      updatedAt:
                        type: string
                        example: '2019-08-05T14:17:58.518Z'
        400:
          description: bad request
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: array
                    items:
                      type: object
                      properties:
                        field:
                          type: string
                          example: commentBody
                        message:
                          type: string
                          example: commentBody cannot be empty
        401:
          description: unauthorized access
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: invalid token
        403:
          description: forbidden access
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: you have to be subscribed to comment on a novel
        404:
          description: entity not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: no comment found with the provided id
  '/profiles':
    patch:
      tags:
        - Users
      summary: Updates a user profile
      security:
      - ApiKeyAuth: []
      requestBody:
        description: fields containing user data
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserProfileInput'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/UserProfileInput'
        required: false
      responses:
        200:
          description: profile successfully updated
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Profile'
        400:
          description: invalid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StandardServerResponse'
        404:
          description: user not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StandardServerResponse'
        409:
          description: email already exist
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StandardServerResponse'
        500:
          description: server error
          content:
            application/json:
              schema:
                type: object
components:
  schemas:
    UserRegisterInput:
      required:
        - firstName
        - lastName
        - email
        - password
      type: object
      properties:
        firstName:
          type: string
          example: john
        lastName:
          type: string
          example: doe
        email:
          type: string
          example: johndoe@email.com
        password:
          type: string
          example: Flyplanex22
    UserLoginInput:
      properties:
        email:
          type: string
          example: johndoe@email.com
        password:
          type: string
          example: Flyplanex22
    NovelInput:
      required:
        - title
        - description
        - body
        - genre
      type: object
      properties:
        title:
          type: string
          example: Think Big
        description:
          type: string
          example: Learn how to think big
        body:
          type: string
          example: There are five steps to thinking big...
        genre:
          type: string
          example: Action
    UserProfileInput:
      type: object
      properties:
        firstName:
          type: string
          example: john
        lastName:
          type: string
          example: doe
        email:
          type: string
          example: johndoe@email.com
        avatarUrl:
          type: string
          example: ''
    AuthResponse:
      properties:
        token:
          type: string
        id:
          type: integer
        bio:
          type: string
    ForgotPasswordUser:
      required:
      - email
      type: object
      properties:
        email:
          type: string
          example: example@gmail.com
    StandardServerResponse:
      type: object
      properties:
        status:
          type: string
          example: success
        message:
          type: string
          example: internal server error 
    Profile:
      required:
      - id
      - bio
      - image
      - following
      type: object
      properties:
        id:
          type: integer
          example: 1
        bio:
          type: string
          example: I love novels
        image:
          type: string
          example: ''
        following:
          type: boolean
          example: true
  securitySchemes:
    bearerToken:
      type: apiKey
      name: Authorization
      in: header
