export const up = queryInterface => queryInterface.bulkInsert('Novels', [{
  id: '7f45df6d-7003-424f-86ec-1e2b36e2fd14',
  title: 'hancock',
  description: 'A',
  slug: 'hancock',
  body: 'abcd',
  genreId: 'ffe299b9-889b-4ad3-86cf-138cd57d5aab',
  authorId: '122a0d86-8b78-4bb8-b28f-8e5f7811c456',
  readTime: 1,
  coverImgUrl: 'https://res.cloudinary.com/allebd/image/upload/v1567555891/dahlia/back5unsplash.jpg',
  thumbImgUrl: 'https://res.cloudinary.com/allebd/image/upload/v1567524086/dahlia/holdstillbookcover.png',
  createdAt: new Date(),
  updatedAt: new Date()
},
{
  id: '8bd8c0ec-3b50-4228-bb71-e617c7b8d3b5',
  title: 'bancock',
  description: 'A',
  slug: 'bancock',
  body: 'abcd',
  genreId: 'ffe299b9-889b-4ad3-86cf-138cd57d5aab',
  authorId: '122a0d86-8b78-4bb8-b28f-8e5f7811c456',
  readTime: 1,
  coverImgUrl: 'https://res.cloudinary.com/allebd/image/upload/v1567555891/dahlia/back5unsplash.jpg',
  thumbImgUrl: 'https://res.cloudinary.com/allebd/image/upload/v1567524086/dahlia/sugarrunbookcover.png',
  createdAt: new Date(),
  updatedAt: new Date()
},
{
  id: '32900c25-def1-43e0-961d-41848cc4c506',
  slug: 'religion-versus-spirituality',
  title: 'Religion And Spirituality',
  description: 'A beautiful take on religion and Spirituality',
  body: 'Religion and Christianity proposes that all the answers can be found in the Bible, while Christianity is all bout searching for anwsers.',
  authorId: '122a0d86-8b78-4bb8-b28f-8e5f7811c456',
  genreId: 'ceb59aa0-b10d-4f37-a0d5-925b38876db4',
  coverImgUrl: 'https://res.cloudinary.com/allebd/image/upload/v1567555877/dahlia/back8unsplash.jpg',
  thumbImgUrl: 'https://res.cloudinary.com/allebd/image/upload/v1567524086/dahlia/QueenOfHearts.png',
  readTime: 1,
  createdAt: new Date(),
  updatedAt: new Date()
},
{
  id: 'b22bf69f-2f61-46cc-84b6-97fabf3e22a3',
  slug: 'a-game-of-thrones',
  title: 'A Game of Thrones',
  description: 'A 7-part series of the power struggle of seven kingdoms',
  body: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris arcu ipsum, sagittis eu dapibus sed, pulvinar suscipit magna. Mauris iaculis rutrum ipsum in lobortis. Quisque ullamcorper at odio ac tristique. Vivamus vel risus vitae lorem varius consequat at quis urna.',
  authorId: '122a0d86-8b78-4bb8-b28f-8e5f7811c456',
  genreId: 'e4427fcd-d1dd-480d-98a6-bb08d5e4d4aa',
  coverImgUrl: 'https://res.cloudinary.com/allebd/image/upload/v1567555877/dahlia/back8unsplash.jpg',
  thumbImgUrl: 'https://res.cloudinary.com/allebd/image/upload/v1567524086/dahlia/QueenOfHearts.png',
  readTime: 1,
  createdAt: new Date(),
  updatedAt: new Date()
},
{
  id: '4f8fd30c-a498-4173-8d8c-dd2729bb499b',
  slug: 'half-of-a-yellow-sun',
  title: 'Half of A Yellow Sun',
  description: 'A tale of a yellow sun',
  body: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris arcu ipsum, sagittis eu dapibus sed, pulvinar suscipit magna. Mauris iaculis rutrum ipsum in lobortis. Quisque ullamcorper at odio ac tristique. Vivamus vel risus vitae lorem varius consequat at quis urna.',
  authorId: 'fb94de4d-47ff-4079-89e8-b0186c0a3be8',
  genreId: 'da86915a-6d4d-455f-8b44-5c4b8221ebf6',
  coverImgUrl: 'https://res.cloudinary.com/allebd/image/upload/v1567555878/dahlia/back2unsplash.jpg',
  thumbImgUrl: 'https://res.cloudinary.com/allebd/image/upload/v1567524085/dahlia/arsonistbookcover.png',
  readTime: 1,
  createdAt: new Date(),
  updatedAt: new Date()
},
{
  id: '0b2e9ded-22db-4a30-ad03-2e830e277bc0',
  slug: 'what-a-time-to-be-alive',
  title: 'What A Time To Be Alive',
  description: 'The highs of been alive at this point',
  body: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris arcu ipsum, sagittis eu dapibus sed, pulvinar suscipit magna. Mauris iaculis rutrum ipsum in lobortis. Quisque ullamcorper at odio ac tristique. Vivamus vel risus vitae lorem varius consequat at quis urna.',
  authorId: 'fb94de4d-47ff-4079-89e8-b0186c0a3be8',
  genreId: 'ceb59aa0-b10d-4f37-a0d5-925b38876db4',
  coverImgUrl: 'https://res.cloudinary.com/allebd/image/upload/v1567555876/dahlia/back3unsplash.jpg',
  thumbImgUrl: 'https://res.cloudinary.com/allebd/image/upload/v1567524085/dahlia/foxbookcover.png',
  readTime: 1,
  createdAt: new Date(),
  updatedAt: new Date()
},
{
  id: 'd54bd6cb-6e62-4689-b39f-a2805da0e859',
  slug: 'the-world-is-ours',
  title: 'The World is Ours',
  description: 'Explaining why the world is really ours',
  body: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris arcu ipsum, sagittis eu dapibus sed, pulvinar suscipit magna. Mauris iaculis rutrum ipsum in lobortis. Quisque ullamcorper at odio ac tristique. Vivamus vel risus vitae lorem varius consequat at quis urna.',
  authorId: 'fb94de4d-47ff-4079-89e8-b0186c0a3be8',
  genreId: 'e4427fcd-d1dd-480d-98a6-bb08d5e4d4aa',
  coverImgUrl: 'https://res.cloudinary.com/allebd/image/upload/v1567555877/dahlia/back4unsplash.jpg',
  thumbImgUrl: 'https://res.cloudinary.com/allebd/image/upload/v1567524085/dahlia/artbookcover.png',
  readTime: 1,
  createdAt: new Date(),
  updatedAt: new Date()
},
{
  id: 'fba0989b-efec-4738-a26d-64f3fb86ff25',
  slug: 'we-are-here-again',
  title: 'We Are Here Again',
  description: 'Reminder of our presence again',
  body: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris arcu ipsum, sagittis eu dapibus sed, pulvinar suscipit magna. Mauris iaculis rutrum ipsum in lobortis. Quisque ullamcorper at odio ac tristique. Vivamus vel risus vitae lorem varius consequat at quis urna.',
  authorId: 'fb94de4d-47ff-4079-89e8-b0186c0a3be8',
  genreId: 'e4427fcd-d1dd-480d-98a6-bb08d5e4d4aa',
  coverImgUrl: 'https://res.cloudinary.com/allebd/image/upload/v1567555883/dahlia/back11unsplash.jpg',
  thumbImgUrl: 'https://res.cloudinary.com/allebd/image/upload/v1567524085/dahlia/artbookcover.png',
  readTime: 1,
  createdAt: new Date(),
  updatedAt: new Date()
},
{
  id: '0e0f43a0-2a73-44ee-96b7-e625d31b67e7',
  slug: 'a-day-at-circus',
  title: 'A Day At Circus',
  description: 'Enjoying the beautiful circus',
  body: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris arcu ipsum, sagittis eu dapibus sed, pulvinar suscipit magna. Mauris iaculis rutrum ipsum in lobortis. Quisque ullamcorper at odio ac tristique. Vivamus vel risus vitae lorem varius consequat at quis urna.',
  authorId: 'fb94de4d-47ff-4079-89e8-b0186c0a3be8',
  genreId: '09add0fe-d063-48ce-8e18-0dc590d04dcf',
  coverImgUrl: 'https://res.cloudinary.com/allebd/image/upload/v1567555882/dahlia/back10unsplash.jpg',
  thumbImgUrl: 'https://res.cloudinary.com/allebd/image/upload/v1567524085/dahlia/artbookcover.png',
  readTime: 1,
  createdAt: new Date(),
  updatedAt: new Date()
},
{
  id: 'bf1f8528-36e2-4193-ad43-dba01aff5178',
  slug: 'the-way-life-goes',
  title: 'The Way Life Goes',
  description: 'Life goes a certain way',
  body: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris arcu ipsum, sagittis eu dapibus sed, pulvinar suscipit magna. Mauris iaculis rutrum ipsum in lobortis. Quisque ullamcorper at odio ac tristique. Vivamus vel risus vitae lorem varius consequat at quis urna.',
  authorId: 'fb94de4d-47ff-4079-89e8-b0186c0a3be8',
  genreId: 'ceb59aa0-b10d-4f37-a0d5-925b38876db4',
  coverImgUrl: 'https://res.cloudinary.com/allebd/image/upload/v1567555884/dahlia/back7unsplash.jpg',
  thumbImgUrl: 'https://res.cloudinary.com/allebd/image/upload/v1567524085/dahlia/artbookcover.png',
  readTime: 1,
  createdAt: new Date(),
  updatedAt: new Date()
},
{
  id: '20d1283b-175d-457d-8009-13f5a5144f64',
  slug: 'before-you-came-around',
  title: 'Before you came around',
  description: 'Thank God You Came Around',
  body: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris arcu ipsum, sagittis eu dapibus sed, pulvinar suscipit magna. Mauris iaculis rutrum ipsum in lobortis. Quisque ullamcorper at odio ac tristique. Vivamus vel risus vitae lorem varius consequat at quis urna.',
  authorId: '122a0d86-8b78-4bb8-b28f-8e5f7811c456',
  genreId: 'e4427fcd-d1dd-480d-98a6-bb08d5e4d4aa',
  coverImgUrl: 'https://res.cloudinary.com/allebd/image/upload/v1567555884/dahlia/back7unsplash.jpg',
  thumbImgUrl: 'https://res.cloudinary.com/allebd/image/upload/v1567524085/dahlia/abstractbookcover.png',
  readTime: 1,
  createdAt: new Date(),
  updatedAt: new Date()
},
{
  id: 'b45bdf8c-a9d5-436c-b2f6-f5c0fa56596a',
  slug: 'higher-and-higher',
  title: 'Higher and Higher',
  description: 'Our journey to higher heights',
  body: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris arcu ipsum, sagittis eu dapibus sed, pulvinar suscipit magna. Mauris iaculis rutrum ipsum in lobortis. Quisque ullamcorper at odio ac tristique. Vivamus vel risus vitae lorem varius consequat at quis urna.',
  authorId: 'fb94de4d-47ff-4079-89e8-b0186c0a3be8',
  genreId: 'ceb59aa0-b10d-4f37-a0d5-925b38876db4',
  coverImgUrl: 'https://res.cloudinary.com/allebd/image/upload/v1567555883/dahlia/back9unsplash.jpg',
  thumbImgUrl: 'https://res.cloudinary.com/allebd/image/upload/v1567524085/dahlia/abstractbookcover.png',
  readTime: 1,
  createdAt: new Date(),
  updatedAt: new Date()
},
{
  id: '8b72f73c-8045-4bb8-8646-5acd0edaa408',
  slug: 'we-can-go-till-the-morning',
  title: 'We Can Go Till The Morning',
  description: 'It is morning time, let us go',
  body: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris arcu ipsum, sagittis eu dapibus sed, pulvinar suscipit magna. Mauris iaculis rutrum ipsum in lobortis. Quisque ullamcorper at odio ac tristique. Vivamus vel risus vitae lorem varius consequat at quis urna.',
  authorId: '122a0d86-8b78-4bb8-b28f-8e5f7811c456',
  genreId: 'da86915a-6d4d-455f-8b44-5c4b8221ebf6',
  coverImgUrl: 'https://res.cloudinary.com/allebd/image/upload/v1567555878/dahlia/back6unsplash.jpg',
  thumbImgUrl: 'https://res.cloudinary.com/allebd/image/upload/v1567524085/dahlia/abstractbookcover.png',
  readTime: 1,
  createdAt: new Date(),
  updatedAt: new Date()
},
{
  id: '2d121687-0477-4f94-9480-24a27625986d',
  slug: 'welcome-to-bootcamp',
  title: 'Welcome To Bootcamp',
  description: 'The trials of bootcamp',
  body: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris arcu ipsum, sagittis eu dapibus sed, pulvinar suscipit magna. Mauris iaculis rutrum ipsum in lobortis. Quisque ullamcorper at odio ac tristique. Vivamus vel risus vitae lorem varius consequat at quis urna.',
  authorId: 'fb94de4d-47ff-4079-89e8-b0186c0a3be8',
  genreId: 'e4427fcd-d1dd-480d-98a6-bb08d5e4d4aa',
  coverImgUrl: 'https://res.cloudinary.com/allebd/image/upload/v1567555878/dahlia/back2unsplash.jpg',
  thumbImgUrl: 'https://res.cloudinary.com/allebd/image/upload/v1567524085/dahlia/abstractbookcover.png',
  readTime: 1,
  createdAt: new Date(),
  updatedAt: new Date()
},
{
  id: '3fe74cd4-a460-4921-af40-f0e3c7fcbc8c',
  slug: 'heaven-at-last',
  title: 'Heaven At Last',
  description: 'Finally making heaven',
  body: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris arcu ipsum, sagittis eu dapibus sed, pulvinar suscipit magna. Mauris iaculis rutrum ipsum in lobortis. Quisque ullamcorper at odio ac tristique. Vivamus vel risus vitae lorem varius consequat at quis urna.',
  authorId: 'fb94de4d-47ff-4079-89e8-b0186c0a3be8',
  genreId: 'ceb59aa0-b10d-4f37-a0d5-925b38876db4',
  coverImgUrl: 'https://res.cloudinary.com/allebd/image/upload/v1567555877/dahlia/back4unsplash.jpg',
  thumbImgUrl: 'https://res.cloudinary.com/allebd/image/upload/v1567524085/dahlia/foxbookcover.png',
  readTime: 1,
  createdAt: new Date(),
  updatedAt: new Date()
},
{
  id: 'c27207eb-2aae-4bae-be6a-de6c5ee9fd79',
  slug: 'love-in-the-air',
  title: 'Love In The Air',
  description: 'Love consuming the air',
  body: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris arcu ipsum, sagittis eu dapibus sed, pulvinar suscipit magna. Mauris iaculis rutrum ipsum in lobortis. Quisque ullamcorper at odio ac tristique. Vivamus vel risus vitae lorem varius consequat at quis urna.',
  authorId: 'fb94de4d-47ff-4079-89e8-b0186c0a3be8',
  genreId: 'da86915a-6d4d-455f-8b44-5c4b8221ebf6',
  coverImgUrl: 'https://res.cloudinary.com/allebd/image/upload/v1567555877/dahlia/back4unsplash.jpg',
  thumbImgUrl: 'https://res.cloudinary.com/allebd/image/upload/v1567524085/dahlia/foxbookcover.png',
  readTime: 1,
  createdAt: new Date(),
  updatedAt: new Date()
},
{
  id: 'f13cf121-6cdd-4e2a-a2d7-45d1f3325214',
  slug: 'which-way-nigeria',
  title: 'Which Way Nigeria',
  description: 'Which way Nigeria, which way to go',
  body: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris arcu ipsum, sagittis eu dapibus sed, pulvinar suscipit magna. Mauris iaculis rutrum ipsum in lobortis. Quisque ullamcorper at odio ac tristique. Vivamus vel risus vitae lorem varius consequat at quis urna.',
  authorId: 'fb94de4d-47ff-4079-89e8-b0186c0a3be8',
  genreId: '09add0fe-d063-48ce-8e18-0dc590d04dcf',
  coverImgUrl: 'https://res.cloudinary.com/allebd/image/upload/v1567555877/dahlia/back1unsplash.jpg',
  thumbImgUrl: 'https://res.cloudinary.com/allebd/image/upload/v1567524085/dahlia/foxbookcover.png',
  readTime: 1,
  createdAt: new Date(),
  updatedAt: new Date()
},
{
  id: '929a1f0b-3338-42c0-ade2-71eaa67cc653',
  slug: 'blue-sapphire',
  title: 'Blue Sapphire',
  description: 'The beauty of the blue sapphire',
  body: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris arcu ipsum, sagittis eu dapibus sed, pulvinar suscipit magna. Mauris iaculis rutrum ipsum in lobortis. Quisque ullamcorper at odio ac tristique. Vivamus vel risus vitae lorem varius consequat at quis urna.',
  authorId: '122a0d86-8b78-4bb8-b28f-8e5f7811c456',
  genreId: 'ceb59aa0-b10d-4f37-a0d5-925b38876db4',
  coverImgUrl: 'https://res.cloudinary.com/allebd/image/upload/v1567555884/dahlia/back7unsplash.jpg',
  thumbImgUrl: 'https://res.cloudinary.com/allebd/image/upload/v1567524085/dahlia/forestbookcover.png',
  readTime: 1,
  createdAt: new Date(),
  updatedAt: new Date()
},
{
  id: '52ae0d19-d660-4c8e-a127-fce42371fe7e',
  slug: 'same-old-songs',
  title: 'Same Old Songs',
  description: 'The state of the music industry',
  body: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris arcu ipsum, sagittis eu dapibus sed, pulvinar suscipit magna. Mauris iaculis rutrum ipsum in lobortis. Quisque ullamcorper at odio ac tristique. Vivamus vel risus vitae lorem varius consequat at quis urna.',
  authorId: 'fb94de4d-47ff-4079-89e8-b0186c0a3be8',
  genreId: 'da86915a-6d4d-455f-8b44-5c4b8221ebf6',
  coverImgUrl: 'https://res.cloudinary.com/allebd/image/upload/v1567555877/dahlia/back8unsplash.jpg',
  thumbImgUrl: 'https://res.cloudinary.com/allebd/image/upload/v1567524085/dahlia/enchantmentbookcover.png',
  readTime: 1,
  createdAt: new Date(),
  updatedAt: new Date()
},
{
  id: 'a00bbeaf-b91e-4986-a3fd-485457b00436',
  slug: 'i-remember-those-days',
  title: 'I Remember Those Days',
  description: 'Those glorious days of the past',
  body: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris arcu ipsum, sagittis eu dapibus sed, pulvinar suscipit magna. Mauris iaculis rutrum ipsum in lobortis. Quisque ullamcorper at odio ac tristique. Vivamus vel risus vitae lorem varius consequat at quis urna.',
  authorId: '122a0d86-8b78-4bb8-b28f-8e5f7811c456',
  genreId: 'da86915a-6d4d-455f-8b44-5c4b8221ebf6',
  coverImgUrl: 'https://res.cloudinary.com/allebd/image/upload/v1567555891/dahlia/back5unsplash.jpg',
  thumbImgUrl: 'https://res.cloudinary.com/allebd/image/upload/v1567524085/dahlia/arsonistbookcover.png',
  readTime: 1,
  createdAt: new Date(),
  updatedAt: new Date()
},
{
  id: '9c3fba74-1307-4f51-987d-dcb1a9a8abee',
  slug: 'in-your-arms',
  title: 'In Your Arms',
  description: 'The warmth of your arms',
  body: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris arcu ipsum, sagittis eu dapibus sed, pulvinar suscipit magna. Mauris iaculis rutrum ipsum in lobortis. Quisque ullamcorper at odio ac tristique. Vivamus vel risus vitae lorem varius consequat at quis urna.',
  authorId: 'fb94de4d-47ff-4079-89e8-b0186c0a3be8',
  genreId: '09add0fe-d063-48ce-8e18-0dc590d04dcf',
  coverImgUrl: 'https://res.cloudinary.com/allebd/image/upload/v1567555883/dahlia/back9unsplash.jpg',
  thumbImgUrl: 'https://res.cloudinary.com/allebd/image/upload/v1567524086/dahlia/holdstillbookcover.png',
  readTime: 1,
  createdAt: new Date(),
  updatedAt: new Date()
},
{
  id: 'b1e32d53-1e1f-4325-a021-7088377a7d22',
  slug: 'set-on-fire',
  title: 'Set On Fire',
  description: 'The pains of fire',
  body: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris arcu ipsum, sagittis eu dapibus sed, pulvinar suscipit magna. Mauris iaculis rutrum ipsum in lobortis. Quisque ullamcorper at odio ac tristique. Vivamus vel risus vitae lorem varius consequat at quis urna.',
  authorId: '122a0d86-8b78-4bb8-b28f-8e5f7811c456',
  genreId: 'ceb59aa0-b10d-4f37-a0d5-925b38876db4',
  coverImgUrl: 'https://res.cloudinary.com/allebd/image/upload/v1567555878/dahlia/back6unsplash.jpg',
  thumbImgUrl: 'https://res.cloudinary.com/allebd/image/upload/v1567524085/dahlia/forestbookcover.png',
  readTime: 1,
  createdAt: new Date(),
  updatedAt: new Date()
},
{
  id: '23df3b87-2c35-4b5b-a10a-04557309bdb3',
  slug: 'my-home-in-the-woods',
  title: 'my home in the woods',
  description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
  body: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur? Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?',
  authorId: '122a0d86-8b78-4bb8-b28f-8e5f7811c456',
  genreId: 'ceb59aa0-b10d-4f37-a0d5-925b38876db4',
  readTime: 3,
  coverImgUrl: 'https://res.cloudinary.com/drlcfqzym/image/upload/v1567081040/homepage_large.png',
  thumbImgUrl: 'https://images.penguinrandomhouse.com/cover/9781101911532',
  createdAt: new Date(),
  updatedAt: new Date()
},
{
  id: '7ab400ae-1ee4-48fd-90cd-a906b88fc87c',
  slug: 'the-man-in-the-forest-of-dreams',
  title: 'the man in the forest of dreams',
  description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
  body: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur? Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?',
  authorId: '26099ff1-edfd-46f3-b6a5-aa900c233e2f',
  genreId: 'ceb59aa0-b10d-4f37-a0d5-925b38876db4',
  readTime: 5,
  coverImgUrl: 'https://res.cloudinary.com/drlcfqzym/image/upload/v1567013343/ah-home.jpg',
  thumbImgUrl: 'https://covers1.booksamillion.com/covers/bam/1/53/689/754/153689754X.jpg',
  createdAt: new Date(),
  updatedAt: new Date()
},
{
  id: '958dae52-53dd-4924-ae63-d8cfc82fd57d',
  slug: 'let-us-go-to-the-moon',
  title: 'let us go to the moon',
  description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
  body: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur? Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?',
  authorId: '26099ff1-edfd-46f3-b6a5-aa900c233e2f',
  genreId: 'ceb59aa0-b10d-4f37-a0d5-925b38876db4',
  readTime: 4,
  coverImgUrl: 'https://res.cloudinary.com/drlcfqzym/image/upload/v1567083656/heaven-4349025_1920.jpg',
  thumbImgUrl: 'https://pictures.abebooks.com/isbn/9780399203138-us.jpg',
  createdAt: new Date(),
  updatedAt: new Date()
},
{
  id: '10d42194-2ea2-4c90-aef2-043421952220',
  slug: 'one-way-trip',
  title: 'one way trip',
  description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.  Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum upidatat non proident, sunt in culpa qui officia.',
  body: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur? Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?',
  authorId: '26099ff1-edfd-46f3-b6a5-aa900c233e2f',
  genreId: 'ceb59aa0-b10d-4f37-a0d5-925b38876db4',
  readTime: 4,
  coverImgUrl: 'https://res.cloudinary.com/drlcfqzym/image/upload/v1567083948/claire-rodahaver-o1Sc5VXglNI-unsplash.jpg',
  thumbImgUrl: 'https://pictures.abebooks.com/isbn/9780399203138-us.jpg',
  createdAt: new Date(),
  updatedAt: new Date()
}], {});

export const down = queryInterface => queryInterface.bulkDelete('Novels', null, {});
